# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('lux', models.FloatField()),
                ('rel_humidity', models.FloatField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('no_of_ppl', models.IntegerField()),
            ],
            options={
                'db_table': 'idcdata',
                'managed': True,
            },
        ),
    ]
