# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170101_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckminster1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 111548)),
        ),
        migrations.AlterField(
            model_name='buckminster2',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 112849)),
        ),
        migrations.AlterField(
            model_name='floor1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 117044)),
        ),
        migrations.AlterField(
            model_name='floor3',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 118305)),
        ),
        migrations.AlterField(
            model_name='floor4',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 119891)),
        ),
        migrations.AlterField(
            model_name='gutenberg1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 108805)),
        ),
        migrations.AlterField(
            model_name='gutenberg2',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 110246)),
        ),
        migrations.AlterField(
            model_name='idc1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 107566)),
        ),
        migrations.AlterField(
            model_name='idcdata',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 104695)),
        ),
        migrations.AlterField(
            model_name='mpn1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 106301)),
        ),
        migrations.AlterField(
            model_name='stevejobs1',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 114536)),
        ),
        migrations.AlterField(
            model_name='stevejobs2',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 24, 10, 115876)),
        ),
    ]
