# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170102_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartLvl1_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('LightDuration', models.FloatField()),
                ('NobodyPresent', models.FloatField()),
            ],
            options={
                'db_table': 'ChartL1_Day',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChartLvl3_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('LightDuration', models.FloatField()),
                ('NobodyPresent', models.FloatField()),
            ],
            options={
                'db_table': 'ChartL3_Day',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChartLvl4_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('LightDuration', models.FloatField()),
                ('NobodyPresent', models.FloatField()),
            ],
            options={
                'db_table': 'ChartL4_Day',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level1_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('PaxCount', models.IntegerField()),
                ('LuxValue1', models.FloatField()),
                ('LuxValue2', models.FloatField()),
                ('MaxLux', models.FloatField()),
                ('AvgLux', models.FloatField()),
                ('Present', models.FloatField()),
                ('Absent', models.FloatField()),
                ('LightsDuration', models.FloatField()),
                ('NobodywLights', models.FloatField()),
                ('Temp1', models.FloatField()),
                ('Temp2', models.FloatField()),
                ('AvgTemp', models.FloatField()),
                ('Humidity1', models.FloatField()),
                ('Humidity2', models.FloatField()),
                ('AvgHumidity', models.FloatField()),
            ],
            options={
                'db_table': 'L1_Stats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level3_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('PaxCount', models.IntegerField()),
                ('LuxValue1', models.FloatField()),
                ('LuxValue2', models.FloatField()),
                ('MaxLux', models.FloatField()),
                ('AvgLux', models.FloatField()),
                ('Present', models.FloatField()),
                ('Absent', models.FloatField()),
                ('LightsDuration', models.FloatField()),
                ('NobodywLights', models.FloatField()),
                ('Temp1', models.FloatField()),
                ('Temp2', models.FloatField()),
                ('AvgTemp', models.FloatField()),
                ('Humidity1', models.FloatField()),
                ('Humidity2', models.FloatField()),
                ('AvgHumidity', models.FloatField()),
            ],
            options={
                'db_table': 'L3_Stats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level4_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('PaxCount', models.IntegerField()),
                ('LuxValue1', models.FloatField()),
                ('LuxValue2', models.FloatField()),
                ('MaxLux', models.FloatField()),
                ('AvgLux', models.FloatField()),
                ('Present', models.FloatField()),
                ('Absent', models.FloatField()),
                ('LightsDuration', models.FloatField()),
                ('NobodywLights', models.FloatField()),
                ('Temp1', models.FloatField()),
                ('Temp2', models.FloatField()),
                ('AvgTemp', models.FloatField()),
                ('Humidity1', models.FloatField()),
                ('Humidity2', models.FloatField()),
                ('AvgHumidity', models.FloatField()),
            ],
            options={
                'db_table': 'L4_Stats',
                'managed': True,
            },
        ),
    ]
